import fs from 'fs';
import path from 'path';
import DashboardClient from './DashboardClient';

export default function Page() {
  // Read the static JSON file generated by the Python engine
  // Since we are running Next.js inside the frontend/ directory, we go up one level
  const resultsPath = path.join(process.cwd(), '../outputs/results.json');
  
  let data = null;
  try {
    const fileContents = fs.readFileSync(resultsPath, 'utf8');
    data = JSON.parse(fileContents);
  } catch (error) {
    console.error("Could not read results.json", error);
  }

  if (!data) {
    return (
      <div className="flex items-center justify-center min-h-screen bg-ink text-paper font-sans">
        <div className="text-center">
          <p className="text-signal-down mb-2 font-mono">Error</p>
          <h1 className="text-xl font-display">Data Not Found</h1>
          <p className="text-sm text-gray-400 mt-2 max-w-md mx-auto">
            Run the Python backtest engine first to generate outputs/results.json.
          </p>
        </div>
      </div>
    );
  }

  return (
    <main className="min-h-screen bg-ink text-paper font-sans selection:bg-accent selection:text-ink">
      <DashboardClient data={data} />
    </main>
  );
}
